// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "apiKey": string;
      "apiEndpoint": string;
      "temperature": number;
      "systemPrompt": string;
      "apiKeyQwen": string;
      "apiKeyDeepseek": string;
      "currentModelId": string;
      "useRag": boolean;
      "embeddingApiKey": string;
      "embeddingApiEndpoint": string;
      "embeddingModelName": string;
      "embeddingDimensions": number;
      "customButtons": string;
      "lastUsedSessionId": string;
      "chatSessionList": string;
    };
  }
}
